### ISSUE TITLE
Radio icons below the start and end times form for plotting

### ISSUE THREAD

**Issue by lukecampbell** [glos/habs_portal#107]
The radio icons for (Example)
- 5 days
- 30 days
- 90 days

**Comment by lukecampbell** [comment]
LoE 4 hrs (plus or minus 3hrs)

**Comment by cgalvarino** [comment]
@kkoch @everhamme What are these time spans relative to?  The end date?  And what happens when you have params from different stations that have completely different time ranges?

**Comment by kkoch** [comment]
This really is an "ed" question, but I would surmise it would be from "today", eg. previous 5 days whether or not there was data.  Therefore it shouldn't matter (I think) on multi-plotting with the stations having different ranges since if the station didn't report for these days, the user wouldn't get data values.  I guess that is also assuming that the portal has built in charting even if there are no values (a flat-line).

**Comment by cgalvarino** [comment]
Team, this is what I am cranking out right now.  Comments on the quick plot?  Basically its job is to set your start/end times for you and refresh the chart.

I have also taken the liberty of shortening any looooooooooooooong var names that appear below the chart.

![quick_plot](https://cloud.githubusercontent.com/assets/180985/7395498/42163fee-ee68-11e4-86b8-164749fda94a.png)

**Comment by tslawecki** [comment]
Functionality is good, FWIW I'd been thinking of having the button label be "Last 5 days", "Last 30 days", "Last 90 days" and obviating the need for the "Quick Plot" label above - space permitting of course. Perhaps the buttons would also refresh the plot automatically?

**Comment by cgalvarino** [comment]
Space is tight (the same view is used on the station page as well as the plot page), and, yes, hitting the button does update the min/max times as well as the graph.  How about this?

![last](https://cloud.githubusercontent.com/assets/180985/7400595/1a085612-ee8c-11e4-82c1-dadddb56133e.png)

**Comment by tslawecki** [comment]
Works For Me!
