### ISSUE TITLE
Specific NOAA stations have bad source reference urls

### ISSUE THREAD

**Issue by christensenmichael0** [glos/habs_portal#158]
Station Name: NOAA GLERL WE2 (present source reference url: http://www.glerl.noaa.gov/res/waterQuality/habsTracker.html

Station Name: NOAA GLERL WE13 (present source reference url:
http://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonWLEPreSQL.html

**Comment by Bobfrat** [comment]
@tslawecki Can you provide new urls for the above?

**Comment by tslawecki** [comment]
I think we can go with https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonSQL.php, copying Ed Verhamme in case he has a better idea.



________________________________

**Comment by kkoch** [comment]
I believe the corrected new link should be > https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/habTracker.html 

(versus the one you are suggesting @tslawecki but it's your call)

**Comment by tslawecki** [comment]
Maybe we should check with GLERL ...



________________________________

**Comment by kkoch** [comment]
I'll shoot a quick message to Russ.

**Comment by Bobfrat** [comment]
Any updates here?

**Comment by kkoch** [comment]
GLERL forwarded the question up the mgmt chain and I haven't heard back.  I'm 99.99% sure that the one I have is correct since it is exactly the same page we were linking to before with an updated URL.  Plus I don't think they even knew we were linking to them, so the only reason I could think of it changing is if they want redirected users to go someplace different. So let's just go with the one I provided above and we can adjust if/once they get back to me. https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/habTracker.html

**Comment by christensenmichael0** [comment]
@Bobfrat @kkoch I've implemented this
