### ISSUE TITLE
Marker Clustering and Color

### ISSUE THREAD

**Issue by lukecampbell** [glos/habs_portal#47]
Can we figure out a way so that the markers, when close together, don't intersect in a obtrusive way. **hint: marker-cluster**

Also it would be good to have a color that's not identical to the city color on the map base tiles.
![screen shot 2015-03-23 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/1155163/6789898/261b2ecc-d17a-11e4-9a2d-e96d960273dd.png)

**Comment by cgalvarino** [comment]
@lukecampbell Not clustering yet, but I like the Leaflet.awesome-markers.  What do you think?  Easy to manipulate the contents, and w/ just a little tweak of the src, I could put text (i.e. scalar values) in place of the fa-fa.

![fa](https://cloud.githubusercontent.com/assets/180985/6817479/47abfd02-d277-11e4-8569-72d994529503.png)

**Comment by cgalvarino** [comment]
Pfft, I see it all over OOI now that I look.  So I know it's a go.

**Comment by cgalvarino** [comment]
@lukecampbell I played w/ clustering, and my hostile feelings toward clustering aside, I do think it is more distracting than anything.  Especially since we have so few points.  I do see where these 2 obs collide, and the new font awesome markers make that even harder to see.  So I vote that we either fudge the positions of each a little to the E and W, or we could use smaller markers.  This is one of those cases where I think we should wait until someone complains.  If we were dealing w/ 100s of dots, it would be another story IMHO.
